# Generated by Django 3.1.7 on 2021-03-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210312_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
