# Generated by Django 3.1.7 on 2021-03-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210312_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='complited',
            field=models.BooleanField(default=False),
        ),
    ]
